### ISSUE TITLE
Minecraft crashing with configurablebeacons

### ISSUE THREAD

**Issue by dabumsti** [ephys/ConfigurableBeacons#2]
[crash-2021-03-23_17.08.24-fml.txt](https://github.com/Ephys/ConfigurableBeacons/files/6191135/crash-2021-03-23_17.08.24-fml.txt)

**Comment by ephys** [comment]
I think you're missing CookieCore: https://www.curseforge.com/minecraft/mc-mods/cookiecore

My bad for not properly declaring that dependency

**Comment by dabumsti** [comment]
Oh ok didn't know that, thought I only need Forge

Thanks for your help
